### ISSUE TITLE
გამშვების პრობლემა ubuntu 22.04-ზე

### ISSUE THREAD

**Issue by kunaia** [pgagnidze/ena#19]
ინსტრუქციის მიხედვით გადმოვწერე და დავაყენე ena. ვცადე `ena -h`-ის გაშვება თუმცა ასეთ რამეს წერს:

/usr/bin/lua5.1: /usr/local/share/lua/5.1/ena/parser.lua:155: attempt to call field 'pack' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/ena/parser.lua:155: in function 'node'
        /usr/local/share/lua/5.1/ena/parser.lua:162: in main chunk
        [C]: in function 'require'
        ...usr/local/lib/luarocks/rocks-5.1/ena/0.0.2-1/bin/ena:6: in main chunk
        [C]: ?

რამეს არასწორად ვაკეთებ თუ რა პრობლემაა ვერ მივხვდი.

**Comment by pgagnidze** [comment]
Fixed in https://github.com/pgagnidze/ena/commit/6681501ac2b83d0552527a4da8234a6db65883ac
